FROM consul


#RUN apt-get update; apt-get upgrade -y ; apt-get install telnet
RUN apk update; apk upgrade; apk add mysql-client busybox-extras 

COPY docker/consul.json docker/server.json docker/mysql.json /consul/config/
