version: '3'

services:
  primeapp:
    image: delgemoon/primeapp-be:develop-build
    build:
      context: ./
      dockerfile: Dockerfile.backend
    ports:
      - "5001:8080"
    environment:
      - TF_DEV=true
    # export G_ID=$(id -g $(whoami))
    # export U_ID=$(id -g $(whoami))
    user: ${U_ID:-0}:${G_ID:-0}
    tty: true
    working_dir: /opt/app
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: ["./bin/prime"]
  ui:
    image: delgemoon/prime-fe:develop-build
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    ports:
      - "5000:8080"
    # export G_ID=$(id -g $(whoami))
    # export U_ID=$(id -g $(whoami))
    user: ${U_ID:-0}:${G_ID:-0}
    tty: true
    working_dir: /opt/app
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: ["http-server", "dist"]

