FROM rabbitmq:3.7-management

# enable the consul plugin.
RUN rabbitmq-plugins enable --offline rabbitmq_peer_discovery_consul

# define the build enviroment.
ENV BUILD=DEV  


# update the box.
RUN apt-get update; apt-get upgrade -y; \
    apt-get install curl -y 

# execute the custom script.
ADD init_rabbitmq.sh /etc/rabbitmq
RUN bash -c '/etc/rabbitmq/init_rabbitmq.sh'


