FROM consul


#RUN apt-get update; apt-get upgrade -y ; apt-get install telnet
RUN apk update; apk upgrade; apk add mysql-client busybox-extras 

COPY consul.json server.json mysql.json /consul/config/
